= Test Driven para documentar RESTful (2/2)
Jorge Aguilera
2016-2-19
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, grails, restful, test-driven
:idprefix:

== Spring-rest-doc and Rest-Assured

Si has leído el primer link:twitterpeople_1_2.html[post] de esta serie recordarás que nuestro objetivo
 es crear una aplicación Grails RESTful que incluya una documentación lo suficientemente clara, precisa y actualizada para
 que un consumidor de nuestro recurso pueda comprender y utilizar el API.

Para ello hemos creado una aplicación que ofrece un recurso *Person* y que se alimenta de usuarios de Twitter. Esta
aplicación es muy básica y simplemente nos sirve para tener un API sobre el que demostrar cómo utilizar Test-Driven
para tener una documentación actualizada y fiable.

link:https://github.com/spring-projects/spring-restdocs/[Spring-rest-doc] es un proyecto de Spring cuya idea es
 utilizar documentación creada por nosotros, con AsciiDoctor, junto con documentación creada por pruebas de forma
 automática, usando fuertemente Spring MVC Test. El problema es que Spring MVC Test no es fácil de utilizar en
 una aplicación Grails (o al menos yo no lo he conseguido).

link:https://github.com/jayway/rest-assured[Rest Assured] por otra parte es un proyecto que proporciona un
extenso DSL orientado a testear servicios REST de una forma cómoda en Java (y por supuesto en Groovy) por lo que
la unión de ambas herramientas nos permitirá desarrollar unos test claros y muy "groovieros"

== Configurando dependencias

[source.groovy]
./build.gradle
----
...
plugins {
    id "org.asciidoctor.convert" version "1.5.2"
}

ext {
...
    springRestdocsVersion = '1.1.0.M1'              // <1>
    snippetsDir = file('build/generated-snippets')  // <2>
}

test {
    outputs.dir snippetsDir  // <2>
}

asciidoctor {
    attributes 'snippets': snippetsDir  // <2>
    inputs.dir snippetsDir
    dependsOn integrationTest           // <3>
}

jar {
    dependsOn asciidoctor
    from ("${asciidoctor.outputDir}/html5") {
        into 'static/docs'              // <4>
    }
}
----
<1> A día de hoy la versión última que funciona se encuentra en estado M1
<2> Usaremos este directorio para alojar los "snippets" generados automáticamente por los test
<3> La tarea asciidoctor generará la documentación únicamente si todos los test han sido correctos
<4> Tenemos la posibilidad de incluir la documentación dentro del propio jar para que sea accesible vía web


== Preparando nuestra documentación

La documentación de todo proyecto debería ser parte del proyecto y como tal encontrarse versionada. Para ello
nos crearemos el directorio src/docs/asciidoc donde alojaremos nuestros documentos AsciiDoc.

Para este ejemplo usaremos un simple *Index* pero en los proyectos de referencia puedes encontrar ejemplos mucho
más completos (un apidoc, getting-started, ..).

[source.asciidoc]
./src/docs/asciidoc/index.adoc
----

 blablabla ... TwitterPeople es un simple ejemplo de cómo usar pruebas unitarias de servicios
 REST y usarlas para autodocumentarlas blablabla  <1>

  include :: {snippets}/people/curl-request.adoc[]   // <2>
  include :: {snippets}/people/http-request.adoc[]  // <2>
  include :: {snippets}/people/http-response.adoc[]  // <2>

----
<1> nuestra documentación incluye documentos que serán generados por los test
<2> cada test generará en el directorio oportuno un curl, un request y un response


== Creando un Spec

Para nuestro ejemplo vamos a crear un Spec que testee los recursos /people/ y /people/${username}

[source.groovy]
./src/integration-test/groovy/twitterpeople/PeopleSpec
----

  void "test index"() {

        given:
        def request = given(documentationSpec)
                .accept("application/json")
                .filter(document("people",      // <1>
                preprocessRequest(modifyUris()
                        .scheme("http")
                        .host("localhost")
                        .removePort())))
        when:
        def then = request
                .when()
                .port(8080)
                .get("/people")                 // <2>
                .then()

        then:
        then.assertThat().statusCode(is(200));

    }

----
<1> document("people") generará el snippet en "people" el cual se refencia en el include de index.adoc
<2> get("/people") realizará una petición REST sobre people

Como se puede observar podemos indicar a cada test a relizar dónde queremos que genere los snippets así
como mantener el código al estilo de un test Spock incluso mediante el uso de "where":

[source.groovy]
./src/integration-test/groovy/twitterpeople/PeopleSpec
----

 void "test person #username"() {

         given:
         def request = given(documentationSpec)
                 .accept("application/json")
                 .filter(document("people/${document}", //<1>
                 preprocessRequest(modifyUris()
                         .scheme("http")
                         .host("localhost")
                         .removePort())))
         when:
         def then = request
                 .when()
                 .port(8080)
                 .get("/people/${username}")    // <2>
                 .then()

         then:
         then.assertThat().statusCode(is(200));
         then.assertThat().content('id', equalTo(username));

         where:
         username | document
         'jagedn' | "person1"   // <1>
     }

----
<1> Podemos hacer que para cada caso del test el snippet se genere en un directorio diferente
<2> Recurso a testear personalizado en cada caso del test

NOTE: link:https://twitter.com/JennStrater:[Jenn Strater] tiene un ejemplo de un test sobre un controller más "limpio"
      que el de TwitterPeople en link:https://github.com/jlstrater/gr8data/blob/master/src/test/groovy/gr8data/controllers/CompanyControllerSpec.groovy[GitHub]


== Build

Por último sólo resta generar nuestra aplicación y si no hay ningún error y todos los test se ejecutan correctamente
la tarea asciidoc se encargará de "enmaquetar" nuestros documentos junto con los snippets y de adjuntarlo en nuestro
jar.

== bootRun

Ahora podemos ejecutar nuestra aplicación:

[source.console]
----

$ java -jar twitterpeople.0-1.jar

----

NOTE: Puesto que Twitter4J requiere de un fichero de configuracion con las claves de autentificacion de tu aplicación
en twitter primero deberás crearlo y añadirlas tal como se indica en http://twitter4j.org/en/configuration.html

Gracias a que SpringBot incluye la capacidad de poder acceder a los recursos que se encuentren bajo el directorio
*static* nuestra documentación será también accesible:

[source.console]
----

$ firefox http://localhost:8080/twitterpeople/docs/index.html

----

donde verías la documentación completa generada:


++++
<div id="header">
<h1>TwitterPeople, Grails proxy de usuarios de Twitter</h1>
<div class="details">
<span id="author" class="author">Jorge Aguilera</span><br>
</div>
</div>
<div id="content">
<div id="preamble">
<div class="sectionbody">
<div class="paragraph">
<p>TwitterPeople es un simple ejemplo de cómo usar pruebas unitarias de servicios
REST y usarlas para autodocumentarlas.</p>
</div>
<div class="paragraph">
<p>El único recurso disponible en TwitterPeople es un Person que contiene
un subconjunto de atributos de un usuario de Twitter. Al inicio de la aplicación
únicamente existe un usuario de pruebas para demostrar su funcionalidad. Según se
le solicitan nuevos identificadores la aplicación buscará si ya existe el recurso
en la base de datos y si no existe acudirá a Twitter a recuperarlo. Si a su vez, existe en
Twitter creará un Person en base a los atributos que recupera y a partir de entonces
ya estará disponbile para futuras peticiones.</p>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_people">People</h2>
<div class="sectionbody">
<div class="paragraph">
<p>Podemos recuperar una lista de Person (People) mediante la invocación de un GET:</p>
</div>
<div class="listingblock">
<div class="content">
<pre class="highlightjs highlight"><code class="language-bash" data-lang="bash">$ curl 'http://localhost/people' -i -H 'Accept: application/json'</code></pre>
</div>
</div>
<div class="listingblock">
<div class="content">
<pre class="highlightjs highlight"><code class="language-http" data-lang="http">GET /people HTTP/1.1
Accept: application/json
Host: localhost</code></pre>
</div>
</div>
<div class="listingblock">
<div class="content">
<pre class="highlightjs highlight"><code class="language-http" data-lang="http">HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application:test
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Fri, 19 Feb 2016 10:28:27 GMT
Content-Length: 110

[{"id":"jagedn","description":"no, si yo yaaa ....","followersCount":54,"friendsCount":111,"location":"aqui"}]</code></pre>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_person">Person</h2>
<div class="sectionbody">
<div class="paragraph">
<p>Para obtener los datos de un Person utilizaremos su nick como identificador (en lugar
del Id de Twitter):</p>
</div>
<div class="listingblock">
<div class="content">
<pre class="highlightjs highlight"><code class="language-bash" data-lang="bash">$ curl 'http://localhost/people/jagedn' -i -H 'Accept: application/json'</code></pre>
</div>
</div>
<div class="listingblock">
<div class="content">
<pre class="highlightjs highlight"><code class="language-http" data-lang="http">GET /people/jagedn HTTP/1.1
Accept: application/json
Host: localhost</code></pre>
</div>
</div>
<div class="listingblock">
<div class="content">
<pre class="highlightjs highlight"><code class="language-http" data-lang="http">HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application:test
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Fri, 19 Feb 2016 10:28:27 GMT
Content-Length: 108

{"id":"jagedn","description":"no, si yo yaaa ....","followersCount":54,"friendsCount":111,"location":"aqui"}</code></pre>
</div>
</div>
</div>
</div>
</div>
++++


== Siguientes pasos

El Spec creado es una primera versión y seguramente podría/debería ser mejorado.
Como he comentado, el link:https://github.com/jlstrater/gr8data/blob/master/src/test/groovy/gr8data/controllers/CompanyControllerSpec.groovy[test] de
Jenny es más "limpio" pero por otra parte el nuestro usa alguna funcionalidad extra que puede ser interesante a tener en cuenta.

Por otra parte el DSL que ofrece link:https://github.com/jayway/rest-assured[Rest Assured] es muy completo y requiere de un estudio
más profundo para poder aprovecharlo mejor. De todas formas creo que el ejemplo visto debería servir para no hacerle
 pereza e incluir un componente tan importante como una buena documentación en tus entregas.

